# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - 'master'
  - 'develop'
  - 'feature/*'
  - 'release/*'

name: $(Build.DefinitionName)-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)
pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DeleteFiles@1
    displayName: 'Remove robots.txt in production'
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
    inputs:
      Contents: 'public/robots.txt'

  - task: Docker@2
    displayName: 'Docker - Test'
    condition: and(succeeded(), not(eq(variables['Build.SourceBranchName'], 'main')))
    inputs:
      containerRegistry: ''
      repository: ''
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildId)
        latest

  - task: Docker@2
    displayName: 'Docker - Acc'
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'acceptance'))
    inputs:
      containerRegistry: ''
      repository: ''
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildId)
        latest

  - task: Docker@2
    displayName: 'Docker - Prod'
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
    inputs:
      containerRegistry: ''
      repository: ''
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildId)
        latest

