import * as fs from 'fs';
import * as path from 'path';
import { RootObject } from 'tokens/tokens';
import util from 'util';

const inDir = process.argv[2].split('=')[1];
const outDir = process.argv[3].split('=')[1];
const tokensPath = path.resolve(__dirname, inDir);
const themePath = path.resolve(__dirname, outDir);

fs.readFile(`${tokensPath}/tokens.json`, 'utf8', (err, data) => {
  const tokens = JSON.parse(data) as RootObject;
  const colors = Object.entries(tokens.colors).reduce(
    (acc, [key, obj]) => ({
      ...acc,
      [key.split(' ').join('-').toLocaleLowerCase()]:
        'value' in obj
          ? obj.value
          : Object.entries(obj).reduce(
              (nestedAcc, [nestedKey, nestedObj]) => ({
                ...nestedAcc,
                [nestedKey.split(' ').join('-').toLocaleLowerCase()]: nestedObj.value,
              }),
              {},
            ),
    }),
    {},
  );
  if (colors) {
    fs.writeFile(
      `${themePath}/colors.ts`,
      `
      // DO NOT MAKE CHANGES TO THIS FILE BY HAND
      // THIS FILE IS AUTOMATICALLY GENERATED BY THE YARN THEME COMMAND
      import { ChakraTheme } from '@chakra-ui/react';
      export const colors: ChakraTheme['colors']  = ${util.inspect(colors, false, 2, false)}`,
      err => {
        console.log(
          err
            ? `Whoops... Something went wrong with generating the colors: ${err}`
            : 'Successfully converted color design tokens!',
        );
      },
    );
  }
});
