const fs = require('fs').promises;
const path = require('path');
const util = require('util');
const lodash = require('lodash');
const polished = require('polished');

const inDir = process.argv[2].split('=')[1];
const outDir = process.argv[3].split('=')[1];
const tokensPath = path.resolve(__dirname, inDir);
const themePath = path.resolve(__dirname, outDir);

const generateTokens = async () => {
  try {
    const data = await fs.readFile(`${tokensPath}/tokens.json`, 'utf8');
    const tokens = JSON.parse(data);

    const colors = Object.entries(tokens.color).reduce(
      (acc, [key, obj]) => ({
        ...acc,
        [lodash.kebabCase(key)]:
          'value' in obj
            ? obj.value
            : Object.entries(obj).reduce(
                (nestedAcc, [nestedKey, nestedObj]) => ({
                  ...nestedAcc,
                  [lodash.kebabCase(nestedKey)]: nestedObj.value,
                }),
                {},
              ),
      }),
      {},
    );

    const breakpoints = Object.entries(tokens.breakpoints).reduce(
      (acc, [key, obj]) => ({
        ...acc,
        [key]: key === 'base' ? polished.em(0) : polished.em(obj.value),
      }),
      {},
    );

    const space = Object.entries(tokens.spacing).reduce(
      (acc, [key, obj]) => ({
        ...acc,
        [key]: polished.rem(obj.value.bottom),
      }),
      {},
    );

    const radii = Object.entries(tokens.radii).reduce(
      (acc, [key, obj]) => ({
        ...acc,
        [lodash.kebabCase(key)]: `${polished.rem(obj.value.topLeft)} ${polished.rem(
          obj.value.topRight,
        )} ${polished.rem(obj.value.topRight)} ${polished.rem(
          obj.value.bottomRight,
        )} ${polished.rem(obj.value.bottomLeft)}`,
      }),
      {},
    );

    const responsiveKeys = Object.keys(tokens.font);
    const textStyles = Object.entries(tokens.font['base']).reduce(
      (acc, [key, _]) => ({
        ...acc,
        [key]: {
          fontFamily: responsiveKeys.reduce(
            (nestedAcc, nestedKey) => ({
              ...nestedAcc,
              [nestedKey]: tokens.font[nestedKey][key].value.fontFamily,
            }),
            {},
          ),
          fontSize: responsiveKeys.reduce(
            (nestedAcc, nestedKey) => ({
              ...nestedAcc,
              [nestedKey]: polished.rem(tokens.font[nestedKey][key].value.fontSize),
            }),
            {},
          ),
          fontWeight: responsiveKeys.reduce(
            (nestedAcc, nestedKey) => ({
              ...nestedAcc,
              [nestedKey]: tokens.font[nestedKey][key].value.fontWeight,
            }),
            {},
          ),
          lineHeight: responsiveKeys.reduce(
            (nestedAcc, nestedKey) => ({
              ...nestedAcc,
              [nestedKey]:
                tokens.font[nestedKey][key].value.lineHeight /
                tokens.font[nestedKey][key].value.fontSize,
            }),
            {},
          ),
          letterSpacing: responsiveKeys.reduce(
            (nestedAcc, nestedKey) => ({
              ...nestedAcc,
              [nestedKey]: polished.em(tokens.font[nestedKey][key].value.letterSpacing),
            }),
            {},
          ),
          textTransform: responsiveKeys.reduce(
            (nestedAcc, nestedKey) => ({
              ...nestedAcc,
              [nestedKey]: tokens.font[nestedKey][key].value.textCase,
            }),
            {},
          ),
          fontStyle: responsiveKeys.reduce(
            (nestedAcc, nestedKey) => ({
              ...nestedAcc,
              [nestedKey]: tokens.font[nestedKey][key].value.fontStyle,
            }),
            {},
          ),
        },
      }),
      {},
    );

    if (colors) {
      await fs.writeFile(
        `${themePath}/colors.ts`,
        `// DO NOT MAKE CHANGES TO THIS FILE BY HAND
        // THIS FILE IS AUTOMATICALLY GENERATED BY THE YARN THEME COMMAND
        import { ChakraTheme } from '@chakra-ui/react';
        export const colors: ChakraTheme['colors']  = ${util.inspect(colors, false, 2, false)}`,
      );
      console.log('Successfully converted color design tokens!');
    }

    if (breakpoints) {
      await fs.writeFile(
        `${themePath}/breakpoints.ts`,
        `
        // DO NOT MAKE CHANGES TO THIS FILE BY HAND
        // THIS FILE IS AUTOMATICALLY GENERATED BY THE YARN THEME COMMAND
        import { ChakraTheme } from '@chakra-ui/react';
        export const breakpoints: ChakraTheme['breakpoints']  = ${util.inspect(
          breakpoints,
          false,
          2,
          false,
        )}`,
      );
      console.log('Successfully converted breakpoints design tokens!');
    }

    if (space) {
      await fs.writeFile(
        `${themePath}/space.ts`,
        `
        // DO NOT MAKE CHANGES TO THIS FILE BY HAND
        // THIS FILE IS AUTOMATICALLY GENERATED BY THE YARN THEME COMMAND
        import { ChakraTheme } from '@chakra-ui/react';
        export const space: ChakraTheme['space']  = ${util.inspect(space, false, 2, false)}`,
      );
      console.log('Successfully converted spacing design tokens!');
    }

    if (radii) {
      await fs.writeFile(
        `${themePath}/radii.ts`,
        `
        // DO NOT MAKE CHANGES TO THIS FILE BY HAND
        // THIS FILE IS AUTOMATICALLY GENERATED BY THE YARN THEME COMMAND
        import { ChakraTheme } from '@chakra-ui/react';
        export const radii: ChakraTheme['radii']  = ${util.inspect(radii, false, 2, false)}`,
      );
      console.log('Successfully converted radii design tokens!');
    }

    if (textStyles) {
      await fs.writeFile(
        `${themePath}/textStyles.ts`,
        `
        // DO NOT MAKE CHANGES TO THIS FILE BY HAND
        // THIS FILE IS AUTOMATICALLY GENERATED BY THE YARN THEME COMMAND
        import { ChakraTheme } from '@chakra-ui/react';
        export const textStyles: ChakraTheme['textStyles']  = ${util.inspect(
          textStyles,
          false,
          2,
          false,
        )}`,
      );
      console.log('Successfully converted font design tokens!');

      await fs.writeFile(
        `${themePath}/components/heading.ts`,
        `
        // DO NOT MAKE CHANGES TO THIS FILE BY HAND
        // THIS FILE IS AUTOMATICALLY GENERATED BY THE YARN THEME COMMAND
        import { ComponentStyleConfig } from '@chakra-ui/react';
        export const heading: ComponentStyleConfig  = {
          sizes: ${util.inspect(textStyles, false, 2, false)}
        }`,
      );
      console.log('Successfully converted font design tokens!');
    }
  } catch (err) {
    console.log(`Whoops... Something went wrong with reading the JSON file: ${err}`);
  }
};

generateTokens();
