// DO NOT MAKE CHANGES TO THIS FILE BY HAND
// THIS FILE IS AUTOMATICALLY GENERATED BY THE YARN THEME COMMAND
import { ChakraTheme } from '@chakra-ui/react';
export const breakpoints: ChakraTheme['breakpoints'] = {
  base: '0em',
  sm: '20em',
  md: '30em',
  lg: '48em',
  xl: '64em',
  '2xl': '75em',
};
