// DO NOT MAKE CHANGES TO THIS FILE BY HAND
// THIS FILE IS AUTOMATICALLY GENERATED BY THE YARN THEME COMMAND
import { ChakraTheme } from '@chakra-ui/react';
export const colors: ChakraTheme['colors'] = {
  brand: { 'han-purple': '#5115f7ff' },
  foundation: { 'rich-black': '#121212ff', white: '#ffffffff' },
  gray: { '50': '#f2f2f2ff', '100': '#c4c4c4ff', '200': '#646464ff' },
};
