// DO NOT MAKE CHANGES TO THIS FILE BY HAND
// THIS FILE IS AUTOMATICALLY GENERATED BY THE YARN THEME COMMAND
import { ChakraTheme } from '@chakra-ui/react';
export const radii: ChakraTheme['radii'] = {
  sm: '0.3125rem 0.3125rem 0.3125rem 0.3125rem 0.3125rem',
};
