// DO NOT MAKE CHANGES TO THIS FILE BY HAND
// THIS FILE IS AUTOMATICALLY GENERATED BY THE YARN THEME COMMAND
import { ChakraTheme } from '@chakra-ui/react';
export const space: ChakraTheme['space'] = {
  '2': '0.125rem',
  '4': '0.25rem',
  '8': '0.5rem',
  '16': '1rem',
  '32': '2rem',
  '64': '4rem',
  '128': '8rem',
  '256': '16rem',
};
